services:
  backend:
    build: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - ollama
    networks:
      - testing-network

  frontend:
    build: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - testing-network

  ollama:
    build: ollama
    ports: 
      - 11434:11434
    volumes:
      - ./ollama:/app/ollama
    networks:
      - testing-network
    entrypoint: ['/usr/bin/bash', 'app/ollama/pull-phi3.sh']

networks:
  testing-network:
    driver: bridge
