version: '3'
services:
  backend:
    build:
      context: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=production

  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend